# src/AttendanceBundle/Resources/config/doctrine/Order.orm.yml
AttendanceBundle\Entity\Order:
    type: entity
    table: tb_order
    id:
        id:
            type: integer
            length: 3
            generator: { strategy: AUTO }
            options:
                unsigned: true
    oneToMany:
        tickets:
          targetEntity: Ticket
          mappedBy: order